apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-teste
  labels: 
    app: api-teste
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: api-teste
  template:
    metadata:
      labels:
        app: api-teste
    spec:
      containers:
      - name: api-teste
        image: rafaelnascdev/api-test:{{ .Values.image.tag}}
        ports:
        - containerPort: {{ .Values.container.port }}