kind: Service
apiVersion: v1
metadata:
  name: api-teste
spec:
  type: NodePort
  selector:
    app: api-teste
  ports:
  - protocol: TCP
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    nodePort: {{ .Values.service.port }}